# Generated by Django 3.2.20 on 2023-08-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название товара'),
        ),
    ]
