# Generated by Django 3.2.20 on 2023-08-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(default=None, to='catalog.Size', verbose_name='Размеры'),
        ),
    ]
