# Generated by Django 3.2.20 on 2023-08-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'категория размера',
                'verbose_name_plural': 'категории размера',
            },
        ),
        migrations.AddField(
            model_name='size',
            name='size_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.sizecategory', verbose_name='Категория'),
        ),
    ]
